### ISSUE TITLE
Games disk mount error

### ISSUE THREAD

**Issue by billb2050** [agn453/RSTS-E#1]
I'm getting "?PROCESS ERROR IN MOUNT - ?Protection violation" after I try and mount rl01-games.dsk on RSTS/E V07. I have no error messages book and can't find the error by googling. Title page says "for the PDP-11 RSTS/E V10.1 Operating System". But the games description says V07 and up!

I use to play Star Trek on my school's PDP 11/40 running RSTS/E as they say..."back in the day!"

**Comment by agn453** [comment]
I just checked and see that the rl01-games.dsk image file from GitHub is in RSTS level 1.2 format.

That's why you can't use it under RSTS/E V07 (which only supports level 1.1 and the original RSTS disk format which is known as level 0.0).  I'll make a replacement disk image in level 1.1 format and upload it shortly.

**Comment by agn453** [comment]
Correction.  My RSTS V07-07 refuses to mount a level 1.1 disk too - so I've just uploaded a replacement level 0.0 image.  Can you try with the https://github.com/agn453/RSTS-E/blob/master/software/rl01-games-rsts0-0.dsk RL01 disk image instead?

**Comment by billb2050** [comment]
New disks work! Thank you so much.

**Comment by agn453** [comment]
Now that I think of it, the RSTS/E disk format changed somewhere around the V7.2 timeframe, and again with V8.  I don't have a copy of V7.2 installed to verify this.  Glad it's all working for you now.  Thanks for letting me know.  Regards, Tony
