### ISSUE TITLE
Does Adventure require Fortran?

### ISSUE THREAD

**Issue by billb2050** [agn453/RSTS-E#3]
Thanks to you solving a previous issue with the game pack I am able to mount the games pack. I was mostly interested in Star Trek (which runs fine). However,  you pointed out Adventure is also supplied. However if I try and run it, I get...

Using...RSTS/E V7.0

RUN DL0:[100,102]ADVENT.SAV

?Err 28 Open failed for file
in routine “RSTRGM” line 28

from routine “INIT ” line 36

from routine “ADVENT” line 28

Ready

I also tried running this (seems to run OK) first...
RUN DL0:[100,102]ABUILD.SAV

Ready

When I try running it again, I get (not quite the same)...
RUN DL0:[100,102]ADVENT.SAV

?Err 28 Open failed for file
in routine “INIT ” line 78

from routine “ADVENT” line 28

Ready

Thank  You

**Comment by billb2050** [comment]
I thought of this later. Run is probably incorrect.

**Comment by billb2050** [comment]
No after finding a Fortran users guide it appears run is correct

**Comment by agn453** [comment]
Because of the way the support files are opened by ADVENT - you'll need to copy one of the files into your account.

The following copies the main executable to your account and the game text and creates the index and saved game files -

```
PIP SY:ADVENT.SAV=DL0:[100,102]ADVENT.SAV
PIP SY:ATEXT.TXT=DL0:[100,102]ATEXT.TXT
RUN DL0:[100,102]ABUILD.SAV
```

Then to run it just do

```
RUN ADVENT
```

The documentation files included with ADVENT are not very clear as regards running it under RSTS/E.  If you have the Fortran compiler, you can adjust the filenames in the source-code to point to the ATEXT.TXT file in a specific directory (using for example, a system wide logical name like ADV:) and then install the ADVENT.SAV program as a CCL command (like ADVENT).  Since the program is large there's not enough memory to do the set-up from the main executable image, so a first-time user will still need to run ABUILD only once to build the index files ATEXT.DAT and AINDX.DAT.

Tony

**Comment by billb2050** [comment]
Thank you!
